[default]

api_prefix = "/api/v1"
log_file = "@format {env[BASE_DIR]}/logs/ocs.log"
log_level = 10
log_format = "%(asctime)s %(levelname)s %(name)s %(threadName)s : %(message)s"
cors_origins = ["*"]
reload_enable = true
sparql_product_path = "@format {env[BASE_DIR]}/resources/sparql/product.txt"
sparql_products_path = "@format {env[BASE_DIR]}/resources/sparql/products.txt"
sparql_person_path = "@format {env[BASE_DIR]}/resources/sparql/person.txt"
sparql_persons_path = "@format {env[BASE_DIR]}/resources/sparql/persons.txt"
sparql_organisation_path = "@format {env[BASE_DIR]}/resources/sparql/organisation.txt"
sparql_organisations_path = "@format {env[BASE_DIR]}/resources/sparql/organisations.txt"
sparql_service_path = "@format {env[BASE_DIR]}/resources/sparql/service.txt"
sparql_services_path = "@format {env[BASE_DIR]}/resources/sparql/services.txt"
sparql_topic_path = "@format {env[BASE_DIR]}/resources/sparql/topic.txt"
sparql_topics_path = "@format {env[BASE_DIR]}/resources/sparql/topics.txt"
